<?php 
    include('assets/inc/header.inc.php');
    include('assets/inc/home.inc.php');
    include('assets/inc/experience.inc.php');
    include('assets/inc/whatido.inc.php');
    include('assets/inc/portfolio.inc.php');
    include('assets/inc/contact.inc.php');
    include('assets/inc/footer.inc.php'); 
?>